### ISSUE TITLE
Create Basic File Types (HTML, JS, CSS)

### ISSUE THREAD

**Issue by Bright-Verdant** [Bright-Verdant/Gro-Pro-Project#4]

**Comment by RomeVinyaro** [comment]
As a user:
I want to have access to an application with HTML, CSS, and JavaScript 

So that when I create a HTML, CSS, and JavaScript file that interact with each other

Acceptance Criteria:
1) Create html file
2) Create css file
3) Create js file
4) Link html with css and js
