### ISSUE TITLE
Code in CSS for our starter page

### ISSUE THREAD

**Issue by Bright-Verdant** [Bright-Verdant/Gro-Pro-Project#6]
Code in the CSS file and HTML file as needed so our starter page resembles the wireframe

https://files.slack.com/files-pri/T045LQ7A7TQ-F04KCE47GH1/image.png

Alternatively redo the wireframe and code to that standard

**Comment by RomeVinyaro** [comment]
As a user:
I want to add basic beginner code to the css

So that the web application resembles the wireframe

Acceptance Criteria:

1. CSS resembles wireframe
2. CSS is linked to the index file
